name = "complexitylib"
version = "0.1.0"
defaultTargets = ["Complexitylib"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "990e65a685bed413f43b139db900a36ad5322a10"

[[lean_lib]]
name = "Complexitylib"
